# ===============================
# Configuración Base de Datos
# ===============================

# URL de conexión (usa Railway si existen las variables, sino local)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/rcgeometrica?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

# Usuario y contraseña (Railway o fallback local)
spring.datasource.username=${DB_USER:rafa}
spring.datasource.password=${DB_PASSWORD:Rakolxd1?}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Seguridad Spring Security
# ===============================
spring.security.user.name=${APP_USER:sagrario8}
spring.security.user.password=${APP_PASSWORD:presion8}
